 channels:
    - conda-forge
 dependencies:
    - dlib
    - face_recognition
    - opencv
    - pandas
    - Pillow
    - matplotlib
    - pip
    - pip:
        - retina-face
        - deepface    
        - numpy==1.19.5