 channels:
     - conda-forge
 dependencies:
     - dlib
     - pip:
        - numpy
        - pandas
        - opencv-python==4.1.2.30
        - face_recognition==1.3.0
        - retina-face==0.0.5
        - deepface==0.0.68
        - Pillow==7.1.2